### ISSUE TITLE
AttributeError: 'PapermillExecutePreprocessor' object has no attribute 'set_widgets_metadata'

### ISSUE THREAD

**Issue by b0noI** [nteract/papermill#362]
$ papermill --version
1.0.0 from /opt/anaconda3/lib/python3.7/site-packages/papermill/cli.py (3.7.3)

Notebook executing: https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson3-head-pose.ipynb

```bash
~/tutorials/fastai/course-v3/nbs/dl1$ papermill ./lesson3-head-pose.ipynb ./lesson3-head-pose-out.ipynb
Input Notebook:  ./lesson3-head-pose.ipynb
Output Notebook: ./lesson3-head-pose-out.ipynb
 69%|██████████████████████████████████████████████████████████████████████████████▌                                   | 20/29 [03:51<02:05, 13.93s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [12:06<00:00, 25.06s/it]
Traceback (most recent call last):
  File "/opt/anaconda3/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/papermill/cli.py", line 165, in papermill
    cwd=cwd,
  File "/opt/anaconda3/lib/python3.7/site-packages/papermill/execute.py", line 93, in execute_notebook
    start_timeout=start_timeout,
  File "/opt/anaconda3/lib/python3.7/site-packages/papermill/engines.py", line 57, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/papermill/engines.py", line 309, in execute_notebook
    nb = cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/papermill/engines.py", line 365, in execute_managed_notebook
    preprocessor.preprocess(nb_man, kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/papermill/preprocess.py", line 24, in preprocess
    self.set_widgets_metadata()
AttributeError: 'PapermillExecutePreprocessor' object has no attribute 'set_widgets_metadata'
```

**Comment by MSeal** [comment]
Hmm, how did you install? The root issue is that you have nbconvert 5.4 and not nbconvert 5.5 installed. Our conda-forge feedstock has a rule for nbconvert >= 5.5 which I am guessing fastai might be overwriting incorrectly.

**Comment by b0noI** [comment]
works correctly with 0.19.1. I will check with upgraded nbconvert. BTW i have installed it from pip

**Comment by MSeal** [comment]
The pip install should complain if you have an older nbconvert unless your using an old pip version or a later install pinned it back to 5.4. You can check your nbconvert version with `pip list | grep nbconvert`.

**Comment by b0noI** [comment]
yep, can confirm that I have old nbcovert
